# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- J2EE

pool:
  vmImage: ubuntu-latest

resources:
 repositories:
   - repository: Onlinebookstore
     type: github
     endpoint: My Project
     name: jatla991/onlinebookstore
     ref: J2EE
   - repository: Common_templates
     type: git
     name: Common_templates
   - repository: OnlinebookstoreMain
     type: github
     endpoint: My Project
     name: jatla991/onlinebookstore
     ref: main

stages:
  - stage: 'J2EE'
    jobs:
      - job: 'buildofJ2EE'
        steps:
          - checkout: Onlinebookstore
          - template: build.yml@Common_templates
            parameters:
              buildType: 'java'
              env: 'prod'
  
  - stage: 'Main'
    jobs:
      - job: 'buildfromMain'
        steps:
          - checkout: OnlinebookstoreMain
          - template: build.yml@Common_templates
            parameters:
              buildType: 'java'
              env: 'qa'
      